export OBJS_PATH=$(EC535PROJ_ROOT)/obj/
export LIBS_PATH=$(EC535PROJ_ROOT)/lib/
export BINS_PATH=$(EC535PROJ_ROOT)/bin/
export GLOVE_BIN_PATH=$(BINS_PATH)/glove/
export ARM_BIN_PATH=$(BINS_PATH)/arm/
export EC535PROJ_DIRS = $(OBJs_PATH) $(LIBS_PATH) $(BINS_PATH) $(GLOVE_BIN_PATH) $(ARM_BIN_PATH)
